"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['__main__.py']
APP_NAME = "Secret Message"
DATA_FILES = []
OPTIONS = {
    'iconfile': 'secret.icns',
    'argv_emulation': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Making Secret Messages",
        'CFBundleIdentifier': "com.boubli.osx.message",
        'CFBundleVersion': "0.2.0",
        'CFBundleShortVersionString': "0.2.0",
        'NSHumanReadableCopyright': u"Copyright © 2018, Youssef Boubli, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
